import type { NextPage } from 'next';
import Head from 'next/head';
import { Navigation, ImageWrapped, SearchIconSVG, Box, Hamburger, Sidebar } from 'components';
import daigo from 'public/daigo_white.svg';
import Image from 'next/image';
import Link from 'next/link';
// import { createClient } from 'next-sanity';

// const client = createClient({
//     projectId: '3zonnd0w',
//     dataset: 'production',
//     apiVersion: '2022-08-28',
//     useCdn: false,
// });

const navigationArray = ['Features', 'Style Guide', 'Search'];

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation>
                <Box className="flex items-center w-full h-[70px] bg-navBg text-pageWhite px-5">
                    <ImageWrapped
                        className="w-[100px] h-full"
                        imageComp={<Image src={daigo} layout="fill" objectFit="contain" />}
                    />
                    <div className="hidden md:flex items-center ml-auto">
                        <Link href="#">
                            <p className="navItem">Blog</p>
                        </Link>
                        <Link href="#">
                            <p className="navItem">Features</p>
                        </Link>
                        <Link href="#">
                            <p className="navItem">Style Guide</p>
                        </Link>
                        <div className="w-fit flex items-center gap-1">
                            <p className="text-inherit text-size24 ">Search</p>
                            <SearchIconSVG className="iconSize" />
                        </div>
                    </div>
                    <Hamburger className="w-fit h-8 ml-auto cursor-pointer md:hidden" />
                </Box>
            </Navigation>
            <Sidebar />
        </div>
    );
};

export default Home;

// export async function getStaticProps() {
//     const article = await client.fetch(`*[_type == "article"]`);
//     console.log(article, 'data');
//     return {
//         props: { article },
//     };
// }
