import type { NextPage } from 'next';
import Head from 'next/head';
import {
    PageStructure,
    ImageWrapped,
    SearchIconSVG,
    Article,
    Box,
    Hamburger,
    Sidebar,
    Navigation,
    Title,
    SubscribeForm,
    FooterList,
    FooterListItem,
    MotionBox,
    PageWrapper,
    PageSplitter,
} from 'components';
import { motion } from 'framer-motion';
import daigo from 'public/daigo_white.svg';
import Image from 'next/image';
import Link from 'next/link';
import { navigationArray } from 'utils/pageArrays';
import { hoverVariant } from 'Variants/variants';
import bgPawel from 'public/bgPawel.jpg';
import frontTop from 'public/frontTop.jpeg';
import { about, features, memeberShip, social } from 'utils/pageArrays';
import { ulItem } from 'Variants/variants';

// import { createClient } from 'next-sanity';

// const client = createClient({
//     projectId: '3zonnd0w',
//     dataset: 'production',
//     apiVersion: '2022-08-28',
//     useCdn: false,
// });

const heroAnim = {
    active: {
        y: 0,
        transition: {
            duration: 0.8,
        },
    },
    inactive: {
        y: 20,
    },
};

const Home: NextPage = () => {
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sidebar />
            <PageStructure htmlTag="nav" className="px-5">
                <Navigation />
            </PageStructure>
            <PageStructure htmlTag="main" className="bg-navBg">
                <MotionBox
                    variants={ulItem}
                    initial="inactive"
                    animate="active"
                    className="grid md:grid-cols-six gap-x-5 md:grid-rows-six bg-bgImg overflow-hidden px-5 pt-10 pb-40"
                >
                    <Title
                        className="relative overflow-hidden md:col-span-full md:row-start-1 md:row-end-5"
                        variants={heroAnim}
                        title="Thoughts, stories and ideas"
                    />
                    <MotionBox className="md:row-start-5 md:col-span-6" variants={heroAnim}>
                        <Article
                            aspect="square"
                            description="Being unique is better than being perfect"
                            className="artilceItemMain"
                            href="#"
                            src={frontTop}
                            alt="front_image"
                        />
                    </MotionBox>
                    <Box className="grid grid-cols-2 md:gap-y-10 mt-10 md:mt-0 gap-5 md:row-start-5 md:col-start-7 md:col-span-6">
                        <MotionBox className="col-span-2 w-full hidden md:block" variants={heroAnim}>
                            <SubscribeForm className="lg:w-3/4" transparent />
                        </MotionBox>
                        <MotionBox variants={heroAnim}>
                            <Article
                                aspect="square"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                        </MotionBox>
                        <MotionBox variants={heroAnim}>
                            <Article
                                aspect="square"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                        </MotionBox>
                        <MotionBox variants={heroAnim}>
                            <Article
                                aspect="square"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                        </MotionBox>
                        <MotionBox variants={heroAnim}>
                            <Article
                                aspect="square"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                        </MotionBox>
                    </Box>
                </MotionBox>
                <Box className="-translate-y-20 px-5">
                    <PageSplitter className="overflow-hidden w-full h-fit col-span-2" />
                    <Box className="w-full grid grid-cols-2 gap-5 mt-5">
                        <Article
                            aspect="mixed"
                            className="relative text-pageWhite leading-none cursor-pointer text-size20"
                            withoutDescription
                            description="Being unique is better than being perfect"
                            href="#"
                            src={frontTop}
                            alt="front_image"
                        />
                        <Article
                            aspect="square"
                            className="relative text-pageWhite leading-none cursor-pointer text-size20"
                            withoutDescription
                            description="Being unique is better than being perfect"
                            href="#"
                            src={frontTop}
                            alt="front_image"
                        />
                        <Box className="grid w-full grid-cols-2 md:grid-cols-4 gap-x-5 col-span-2 md:mt-10">
                            <Article
                                aspect="mixed"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                            <Article
                                aspect="mixed"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                            <Article
                                aspect="mixed"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                            <Article
                                aspect="mixed"
                                className="relative text-pageWhite leading-none cursor-pointer text-size20"
                                withoutDescription
                                description="Being unique is better than being perfect"
                                href="#"
                                src={frontTop}
                                alt="front_image"
                            />
                        </Box>
                    </Box>
                </Box>
                {/* <Box className="relative -top-16 px-5"></Box> */}
                <Box className="-translate-y-10 px-5">
                    <Box className="bg-bgImg bg-left-bottom grid grid-cols-2 gap-3 px-2 py-4">
                        <PageSplitter className="overflow-hidden w-full h-fit col-span-2" />
                        <Article
                            aspect="story"
                            className="relative text-pageWhite leading-none cursor-pointer text-size20"
                            withoutDescription
                            description="Being unique is better than being perfect"
                            href="#"
                            src={frontTop}
                            alt="front_image"
                        />
                        <Article
                            aspect="square"
                            className="relative text-pageWhite leading-none cursor-pointer text-size20"
                            withoutDescription
                            description="Being unique is better than being perfect"
                            href="#"
                            src={frontTop}
                            alt="front_image"
                        />
                    </Box>
                </Box>
            </PageStructure>
            <PageStructure htmlTag="footer" className="bg-navBg px-5 -translate-y-10 lg:flex">
                <Box className="w-full md:w-3/4 lg:w-1/2">
                    <ImageWrapped
                        className="w-[150px] h-[100px]"
                        imageComp={<Image src={daigo} layout="fill" objectFit="contain" />}
                    />
                    <SubscribeForm className="overflow-hidden" />
                </Box>
                <Box className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-5 w-full">
                    <FooterList className="text-pageWhite text-size24 md:text-size32" title="Social">
                        <ul className="grid gap-y-3">
                            {social.map(el => (
                                <li key={el.link} className="flex gap-2 items-center text-base hover:underline">
                                    <ImageWrapped
                                        className="relative flex items-center"
                                        imageComp={<Image src={el.img} />}
                                    />

                                    <Link href={`/${el.link}`}>{el.link}</Link>
                                </li>
                            ))}
                        </ul>
                    </FooterList>
                    <FooterList className="text-pageWhite text-size24 md:text-size32" title="About">
                        <FooterListItem className="text-pageWhite text-base grid gap-y-3" listArray={about} />
                    </FooterList>
                    <FooterList className="text-pageWhite text-size24 md:text-size32" title="Features">
                        <FooterListItem className="text-pageWhite text-base grid gap-y-3" listArray={features} />
                    </FooterList>
                    <FooterList className="text-pageWhite text-size24 md:text-size32" title="Membership">
                        <FooterListItem className="text-pageWhite text-base grid gap-y-3" listArray={memeberShip} />
                    </FooterList>
                </Box>
            </PageStructure>
        </PageWrapper>
    );
};

export default Home;

// export async function getStaticProps() {
//     const article = await client.fetch(`*[_type == "article"]`);
//     console.log(article, 'data');
//     return {
//         props: { article },
//     };
// }
